# Generated by Django 5.2.4 on 2025-07-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistration',
            new_name='User',
        ),
    ]
