# Generated by Django 5.2 on 2025-04-17 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
