# Generated by Django 5.2 on 2025-04-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_Api', '0004_userregistration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
