# Generated by Django 5.2.4 on 2025-08-05 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name_doctor', models.CharField(max_length=20)),
                ('core_education', models.CharField(max_length=100)),
                ('topic_education', models.CharField(max_length=100)),
                ('experience', models.IntegerField(default=0)),
                ('about', models.TextField(blank=True, null=True)),
                ('appoint_fee', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('profile_doctor', models.ImageField(upload_to='storage/')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
